### ISSUE TITLE
Problems exporting abstract grammar

### ISSUE THREAD

**Issue by jfschaefer** [KWARC/gf_kernel#1]
There seems to be a bug in the `export` command:
When I try to export an abstract grammar, a concrete grammar gets exported instead.

Example input:

```
abstract Test = {

}
```

```
concrete TestCon of Test = {
    
}
```

```
export Test
```

which results in the file `TestCon.gf` being created (instead of `Test.gf`).

**Comment by kaiamann** [comment]
14f7e9f9d7bfdffbdd752658cb80c25297f7b11f should have fixed this.
